export default [
    {
        id: 1,
        globalId: 11,
        title: 'Футболка UZcotton мужская',
        color: 'белый',
        size: '56',
        price: 522,
        sale_price: 1051,
        total: 0,
        saleTotal: 0,
        value: 0,
        left: 2,
        adress: 'Коледино WB',
        company: 'ООО Вайлдберриз',
        imageUrl: 'Pic1.svg',
        choosen: true,
    },
    {
        id: 2,
        globalId: 21,
        title: 'Силиконовый чехол картхолдер (отверстия) для карт, прозрачный кейс бампер на Apple iPhone XR, MobiSafe',
        color: 'прозрачный',
        size: '',
        price: 10500,
        sale_price: 11500,
        total: 0,
        saleTotal: 0,
        value: 0,
        left: 400,
        adress: 'Коледино WB',
        company: 'ООО Мегапрофстиль',
        imageUrl: 'Pic2.svg',
        choosen: true,
    },
    {
        id: 3,
        globalId: 31,
        title: 'Карандаши цветные Faber-Castell "Замок", набор 24 цвета, заточенные, шестигранные, Faber-Castell',
        color: '',
        size: '',
        price: 123.5,
        sale_price: 475,
        total: 0,
        saleTotal: 0,
        value: 0,
        left: 2,
        adress: 'Коледино WB',
        company: 'ООО Вайлдберриз',
        imageUrl: 'Pic3.svg',
        choosen: true,
    },

]