export default {
    chooseAll: document.querySelector('.choose-all__checkbox'),
    selectItem: document.querySelectorAll('.item__photo'),
    available: document.querySelector('.available__choose-item'),
    minus: document.querySelectorAll('.count__number-minus'),
    number: document.querySelectorAll('.count__number-num'),
    previous: document.querySelectorAll('.previous__value'),
    current: document.querySelectorAll('.current__value'),
    totalPrice: document.querySelector('.total__value'),
    instantPayCheckbox: document.querySelector('.input__checkbox'), 
    btn: document.querySelector('.bill__button-btn'),
    salePercent: document.querySelectorAll('.sale-perc'),
    saleClientPercent: document.querySelectorAll('.sale__client-perc'),
    saleDif: document.querySelectorAll('.sale-dif'),
    saleClientDif: document.querySelectorAll('.sale__client-dif'),
    hider: document.querySelector('.choose-all__hide'),
    modalClose: document.querySelector('.modal__button'),
    modalButton: document.querySelector('.delivery__modal-btn'),
    deliveryModal: document.querySelector('.delivery__modal'),
    modalBackground: document.querySelector('.modal__back'),
    editButton: document.querySelector('.edit__button'),
    main: document.querySelector('body')
};