export default {
    chooseAll: document.querySelector('.choose-all__checkbox'),
    selectItem: document.querySelectorAll('.item__photo'),
    available: document.querySelector('.available__choose-item'),
    minus: document.querySelectorAll('.count__number-minus'),
    number: document.querySelectorAll('.count__number-num'),
    previous: document.querySelectorAll('.previous__value'),
    current: document.querySelectorAll('.current__value'),
    totalPrice: document.querySelector('.total__value'),
    instantPayCheckbox: document.querySelector('.input__checkbox'), 
    btn: document.querySelector('.bill__button-btn'),
    salePercent: document.querySelectorAll('.sale-perc'),
    saleClientPercent: document.querySelectorAll('.sale__client-perc'),
    saleDif: document.querySelectorAll('.sale-dif'),
    saleClientDif: document.querySelectorAll('.sale__client-dif'),
    hider: document.querySelector('.choose-all__hide'),
    // modalClose: document.querySelectorAll('.modal__button'),
    // modalButton: document.querySelectorAll('.delivery__modal-btn'),
    deliveryModal: document.querySelector('.delivery__modal'),
    modalBackground: document.querySelector('.modal__back'),
    editButton: document.querySelector('.edit__button'),
    editPayButton: document.querySelector('.pay__edit-button'),
    main: document.querySelector('body'),
    toAdress: document.querySelector('.to-adress'),
    courier: document.querySelector('.by-courier'),
    payModal: document.querySelector('.pay__modal'),
    placeDel: document.querySelector('.place__button-delivery'),
    placePay: document.querySelector('.place__button-pay'),
    submitButton: document.querySelector('.bill__button'),
    form: document.getElementById('form'),
    receiver: document.querySelector('.bucket__receiver')
};